GET http://localhost:8000
###
GET http://localhost:8000/users
###
GET http://localhost:8000/user/ostroder2@xinhuanet.com
###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"ostroder2@xinhuanet.com",
    "Password":"12Xk4eIO"
}
###
POST http://localhost:8000/createuser
Content-Type: application/json

{
        "id": 4,
        "first_name": "Analise",
        "last_name": "Craigmyle",
        "email": "acraigmyle3@homestead.com",
        "gender": "Female",
        "Password": "ihOg7S"
    }
